apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullname }}
  namespace: des
  labels:
    app.kubernetes.io/name: order-service-app
    app.kubernetes.io/instance: order-service-instance
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: order-service-app
      app.kubernetes.io/instance: order-service-instance
  template:
    metadata:
      labels:
        app.kubernetes.io/name: order-service-app
        app.kubernetes.io/instance: order-service-instance
    spec:
      imagePullSecrets:
        - name: quay-credentials
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
