apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullname }}
  namespace: des
  labels:
    app.kubernetes.io/name: {{ .Values.labels.app.kubernetes.io.name }}
    app.kubernetes.io/instance: {{ .Values.labels.app.kubernetes.io.instance }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.labels.app.kubernetes.io.name }}
      app.kubernetes.io/instance: {{ .Values.labels.app.kubernetes.io.instance }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.labels.app.kubernetes.io.name }}
        app.kubernetes.io/instance: {{ .Values.labels.app.kubernetes.io.instance }}
    spec:
      imagePullSecrets:
        - name: quay-credentials
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}


