apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullname }}
  namespace: kafka
  labels:
    app.kubernetes.io/name: order-service-app
    app.kubernetes.io/instance: order-service-instance
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: order-service-app
    app.kubernetes.io/instance: order-service-instance