apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullname }}
  namespace: des
  labels:
    app.kubernetes.io/name: {{ .Values.labels.app.kubernetes.io.name }}
    app.kubernetes.io/instance: {{ .Values.labels.app.kubernetes.io.instance }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.labels.app.kubernetes.io.name }}
    app.kubernetes.io/instance: {{ .Values.labels.app.kubernetes.io.instance }}