apiVersion: v1
kind: Service
metadata:
  name: {{ include "example-app.fullname" . }}
  namespace: des
  labels:
    {{- include "example-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
      name: http
  selector:
    {{- include "example-app.selectorLabels" . | nindent 4 }}
